# Generated by Django 5.1.6 on 2025-03-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enforce_2fa",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, you will be required to enter an OTP every time you log in.",
            ),
        ),
    ]
