# Generated by Django 5.1.3 on 2025-03-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0003_channelvisit_episodevisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelvisit",
            name="last_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episodevisit",
            name="last_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
