# Generated by Django 5.1.3 on 2025-03-16 23:29

import datetime
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0004_channelvisit_last_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birthdate",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        
        
       
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+10000000000", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
