# Generated by Django 5.1.3 on 2025-03-17 00:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0005_customuser_birthdate_customuser_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(default="US", max_length=2),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
    ]
