# Generated by Django 5.1.3 on 2025-04-08 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0007_searchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed", models.BooleanField(default=False)),
                ("notifications_enabled", models.BooleanField(default=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rating from 1 (lowest) to 5 (highest)",
                        null=True,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_interactions",
                        to="podcasts.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Interaction",
                "verbose_name_plural": "Channel Interactions",
                "unique_together": {("user", "channel")},
            },
        ),
    ]
