# Generated by Django 5.1.3 on 2025-04-27 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0011_reply_comment_seen_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"managed": True, "ordering": ["-publication_date"]},
        ),
        migrations.AlterModelOptions(
            name="episodetranslations",
            options={"managed": True, "ordering": ["-publication_date"]},
        ),
    ]
