# Generated by Django 4.2.23 on 2025-07-21 01:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0016_add_pubdate_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="contribute_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which channels this user has opted to contribute to.",
                to="podcasts.channel",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_contributing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="episode",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="podcasts.channel",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="episodetranslations",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                db_column="episode_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episode_translations",
                to="podcasts.episode",
            ),
        ),
        migrations.AddField(
            model_name="episodetranslations",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("channel", "episode_title")},
        ),
        migrations.AlterUniqueTogether(
            name="episodetranslations",
            unique_together={("episode", "episode_title")},
        ),
        migrations.AddIndex(
            model_name="episode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="episodes_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["episode_title"],
                name="episodes_title_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"],
                name="episodes_desc_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="episodetranslations",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="eptrans_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="episodetranslations",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["episode_title"],
                name="eptrans_title_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="episodetranslations",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"],
                name="eptrans_desc_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
