# Generated by Django 4.2.23 on 2025-07-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0017_customuser_contribute_channels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_contributing",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user is currently running the community agent.",
            ),
        ),
    ]
