# Generated by Django 4.2.23 on 2025-07-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0018_alter_customuser_is_contributing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
