# Generated by Django 4.2.23 on 2025-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0020_supportticket_supportticketattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="support_ticket_limit",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Max open (pending/in-progress) tickets this user can have.",
            ),
        ),
    ]
