# Generated by Django 4.2.23 on 2025-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0021_supportticket_support_ticket_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="support_ticket_limit",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Max open (pending/in-progress) tickets this user can have.",
            ),
        ),
    ]
