# Generated by Django 4.2.23 on 2025-08-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0022_customuser_support_ticket_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportticket",
            name="support_ticket_limit",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="support_ticket_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Max open (pending/in-progress) tickets this user can have.",
            ),
        ),
    ]
