# Generated by Django 4.2.23 on 2025-09-07 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0023_remove_supportticket_support_ticket_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelSearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("language", models.CharField(blank=True, max_length=16, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("first_searched", models.DateTimeField(auto_now_add=True)),
                ("last_searched", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="podcasts.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Search Query",
                "verbose_name_plural": "Channel Search Queries",
                "indexes": [
                    models.Index(
                        fields=["channel", "query"],
                        name="podcasts_ch_channel_473136_idx",
                    ),
                    models.Index(
                        fields=["-last_searched"], name="podcasts_ch_last_se_bc7c23_idx"
                    ),
                ],
            },
        ),
    ]
