# Generated by Django 4.2.23 on 2025-09-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0024_channelsearchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=16),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("first_downloaded", models.DateTimeField(auto_now_add=True)),
                ("last_downloaded", models.DateTimeField(auto_now=True)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("last_user_agent", models.TextField(blank=True, null=True)),
                ("last_filename", models.TextField(blank=True, null=True)),
                ("last_file_path", models.TextField(blank=True, null=True)),
                ("bytes_served", models.BigIntegerField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="podcasts.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Download",
                "verbose_name_plural": "Episode Downloads",
                "indexes": [
                    models.Index(
                        fields=["episode", "language", "-last_downloaded"],
                        name="podcasts_ep_episode_812181_idx",
                    ),
                    models.Index(
                        fields=["user", "-last_downloaded"],
                        name="podcasts_ep_user_id_f7e730_idx",
                    ),
                ],
                "unique_together": {("user", "episode", "language")},
            },
        ),
    ]
