# Generated by Django 4.2.23 on 2025-11-01 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0026_alter_channelvisit_user_alter_episodevisit_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("first_shared", models.DateTimeField(auto_now_add=True)),
                ("last_shared", models.DateTimeField(auto_now=True)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("last_user_agent", models.TextField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="podcasts.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["episode", "-last_shared"],
                        name="podcasts_ep_episode_bc1e85_idx",
                    ),
                    models.Index(
                        fields=["user", "-last_shared"],
                        name="podcasts_ep_user_id_a031c3_idx",
                    ),
                ],
                "unique_together": {("user", "episode")},
            },
        ),
    ]
