# Generated by Django 4.2.23 on 2026-03-22 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0027_episodeshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeAssistantQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("language", models.CharField(blank=True, max_length=16, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("first_asked", models.DateTimeField(auto_now_add=True)),
                ("last_asked", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_queries",
                        to="podcasts.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Assistant Query",
                "verbose_name_plural": "Episode Assistant Queries",
                "indexes": [
                    models.Index(
                        fields=["episode", "query"],
                        name="podcasts_ep_episode_3d7a19_idx",
                    ),
                    models.Index(
                        fields=["-last_asked"],
                        name="podcasts_ep_last_as_35fd8d_idx",
                    ),
                ],
            },
        ),
    ]
