BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
  XXXXX  gettext(u'Community Podcast Generator') XXXXX

  XXXX XXXXXXXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXX
    XXXX  gettext(u"Thank you for volunteering your computer's resources to help generate and process podcast episodes!") XXXX
    XXXX  gettext(u"When you click 'Start Contributing', a lightweight agent running on your machine will fetch new RSS feed entries for your selected channels, transcribe or translate them into usable transcripts, process them locally using your CPU/GPU, and securely return the results. This helps us speed up episode generation and improve quality for the entire community.") XXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXX  gettext(u"Select which channels you'd like to support or choose 'All Channels' to help across the platform.") XXXXX
      XXXXXX  gettext(u"Your contributions run in the background and won't interfere with your normal workflow.") XXXXX
      XXXXXX  gettext(u'You can stop or restart at any time using the button below.') XXXXX
      XXXXX  gettext(u"Soon, we'll introduce a leaderboard to highlight top contributors and a rewards system to thank you for your support.") XXXXX
    XXXXX
  XXXXXX

  XXXX XXXXXXX XXXXXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXXXXXX
      XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXX XXXXXX
    X
      X  gettext(u'Select Channels') 
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'All Channels') XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
      XXXXXX
      BBBBBB
    XXXXXX
  XXXXXX

  XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    X  gettext(u'Start Contributing') 
  XXXXXXXXX
  XX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Status: Idle') XXXX
XXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    XXX
    XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
    XXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
    X

    XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX X
      XXXXX XXX X XXX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXX X XXXXX XXXXXXXXXX X
        XXXXXXX
        XXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
        XXXXXXXXXXXX XXXXXXXXX
      XXX
      XXXXXX XXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX X XXXX X XXX  gettext(u'Stop Contributing') X X XX  gettext(u'Start Contributing') XX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXXXXXX X XXXX X X gettext(u'Status: Contributing') X X X gettext(u'Status: Idle') XX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
XXXXXXX
XX XXXXXX XXXX XXXXX XXXXXX XX
XXXXXXX XXXXXXXXXXXXXX X
  XXXXXXXXX XXXXXXXX XXXXXXXXXXX
  XXXXXXX XXXX XXXXXXXXXXX
  XXXX XXXX XXXXXXXXXXX
  XXXXX X XXXXXXXXXXX
  XXXXXX XXXX XXXXXXXXXXX
  XXXXXXXXXX XXXX XXXXXXXXXXX
X
XX XXXXXXXX XXXXX XX XXXXX XX XX XXXXXXXX XXXXXX XX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXX XX
  XXXXXXX XX
  XXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXXXXXX XXX
  XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX
  XXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX
  XXXXXXXXXXX XX
  XXXXXXXXXXXXXX XXXX XXXXXX
X
XXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXX
  XXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
XXXXXXXX
BBBBBBBB
