XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBB
BBBBB BBBBBBB
  XXXX gettext(u'Favorites') XXXXX
  
  XXXX XXXXXXXXX XXX XXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      BBB BBBBBBB BB BBBBBBBB
          XX 
              XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX 
              XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXX XXXXXX XXXXXXXXXX XXX X XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX
                      BBBB
                          XXXXXXX gettext(u'No image available') XXXXXXXXX
                      BBBBB
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBB
                          XX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'by')  XXXX
                      BBBBB
                      BB BBBBBBBBBBBBBBBBBBBBBBB
                          XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                      BBBBB
                      XXXX XXX XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXX
                      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
                        XXXX XXXXXXXXX XXXXX XXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX gettext(u'Favorites') XX
                                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                                FFFFFFFFFFFFFFFFFFFFFFFF
                            XXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXX XXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX gettext(u'Notifications') XX
                                XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                                FFFFFFFFFFFFFFFFFFFFFFFF
                            XXXXXXX
                            XXXX XXXXXX XXXX XXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX gettext(u'Channel Rating') XX
                                XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBB
                                    FFFFFFFFFFFFF XFFFFFFFFFFFFFX
                                BBBB
                                    XXX
                                BBBBB
                            XXXXXXX
                            XXXX XXXXX XXXXX XXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Total Views') XX
                                XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                                FFFFFFFFFFFFFFFFFFFFFFFF
                            XXXXXXX
                        XXXXXX
                        XXXX XXX XXX XXXX XXXXXXXXX XXX

                  XXXXXX
              XXXXXX
          XXXX
      BBBBB
          XXX gettext(u'No favorite channels found.') XXXX
      BBBBBB
  XXXXXX
  
  XXXX XXXXXXX XXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXX
      XXX gettext(u'Loading more favorite channels...') XXXX
  XXXXXX

  XXXX XXXXXX XXXXXXXXXX XXXXXXX XXX XXXXXXXXXX XXX
  XXXXXXXX
    XXXXX XXXXXXXXXXXXX X X gettext(u'End of list...') XX
    XXXXX XXXXXXXXXXXXXXX X X gettext(u'Loading more channels...') XX
  XXXXXXXXX

  XXXX XXXXXXXX XXXXXX XXXXXXXXXX XXX
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXX XXXX X XX
        XXX XXXXXXX X XXXXXX
        XXX XXXXXXX X XXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XX XXXXXXXX XX XXXXXXXXX XXXXXXX
            
            XX XXXX XXX XXXX XXXXXXX XXXXXX XXXXX XX XXX XXXXXXX
            XX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX X
                XXXXXXX X XXXXX
                XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXXXXXXXXXXXXX X XXXXX X XXXXXXXXXXXXXXX X XXXXXXX
                XXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XX X
                        XX XX XXX XXXXXXXX XXXXXX XX XXXX XXXXX XX XX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXX X
                            XXXXXXX X XXXXXX
                            XXXXXX XXX
                        X
                        XX XXXXXXXXXXXXX X
                            XXXXXX XXXXXXXXXXXXXXXX
                        X
                        XXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
                    XX
                    XXXXXXXXXX XX X
                        XX XX XXXX XX XXXXX XXX XXXX XXXXXXXXXXXX XXXXXX XX XXXX XXXXXX
                        XX XXXXXXXXXXXXXX X
                            XXXXXXX X XXXXXX
                            XXXXXXXXXXXXXXXXX X XXXXX X XXXXXXXXXXXXX X XXXXXXX
                        X XXXX X
                            XX XXXXXX X XXXXXXXXX XXXXXXXXX XX XXXXX XXX XXXX
                            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXX X XXXXX
                            
                            XX XXXXXX XXXX XXX XXXX XXXXXXXX XXXXXXXX XXX XX XXXX XXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXX XX X
                                XXXXXXX X XXXXXX
                                XXXXXXXXXXXXXXXXX X XXXXX X XXXXXXXXXXXXX X XXXXXXX
                            X XXXX X
                                XXXXXXXXXXXXXXXXXXXXX XX X
                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX
                            X
                        X
                        XXXXXXX X XXXXXX
                        XX XX XXXXX XXX XXXXX XXXXXX XXXX XXX XXXXXXXX XXXXXXXXX XXXXX XXX XXXX XX XXXXXXXX XXXXXXX XXXXXXXX
                        XX XXXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                        X
                    XX
                    XXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXXXXX X XXXXXX
                        XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                    XXX
            X
        XXX
    XXX
    XXXXXXXXX

  XXXX XXX XXX XXXXXXX XXXXXXXX XXX
  XXXXXXX
    XXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXX
    X
  XXXXXXXX
BBBBBBBB
