XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX gettext(u'Edit Profile') XXXXX
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Save Changes') XXXXXXXXX
    XXXXXXX
    
    XXXX
    
    XXXX gettext(u'Change Password') XXXXX
    XXX
       gettext(u'Want to change your password?') 
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Click here') XXXXX
    XXXX
XXXXXX
BBBBBBBB
