BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Create Account') XXXXX

    XXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XX XXXX XXXXXX
        XXXXXXXXX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXXXXX XXXX XXXXXXXXXX XXXX XX XXXX X
        XXXXXXXXX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Sign up with GitHub') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX

    XXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'or create an account manually') XXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBXX
      BBBBBBBBBB
      BB BBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXXXXXX gettext(u'Please fix the errors below.') XXXXXXXXX
        XXX XXXXXXXXXXXXX
          BBB BBBBB BB BBBB
            BBB BBBBB BB BBBBBBBBBBBB
              XXXXXXXXXXXXXXXXXXXXXX XXXXX
            BBBBBB
          BBBBBB
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXX
          BBBBBB
        XXXXX
      XXXXXX
    BBBBB

      XXXX XXXXXX XXXXXXXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXX
        
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXXXXXXX
        
        
        
      XXXXXX

      XXXX XXXXXXXX XXXXXX XXXX XXXXXX XXXXXX XXX
XXXX XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Password') XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    FFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Show/Hide password') XX
      XX XXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  
XXXXXX

XXXX XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Confirm Password') XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    FFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Show/Hide password') XX
      XX XXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX




      XXXX XXXXXXXX XXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXX
        XXXX gettext(u'Password Requirements:') XXXXX
        XXXX
          XXXX gettext(u'Must be at least 8 characters long.') XXXXX
          XXXX gettext(u'Cannot be a common password.') XXXXX
          XXXX gettext(u'Cannot be entirely numeric.') XXXXX
          XXXX gettext(u'Should not be too similar to your personal information.') XXXXX
        XXXXX
      XXXXXX

      XXXX XXXXXXX XXXXXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'By checking this box, I acknowledge that I have read and agree to') 
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u"Muse Podcast, LLC's Privacy Notice") 
          XXXX gettext(u', and consent to the collection, anonymized sharing, and sale of data as described.') 
        XXXXXXXX
      XXXXXX

      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Sign Up') XXXXXXXXX
    XXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXX XXXX XXXXXXX XXX XXX XXXXXXX XX XXXX XXXX XXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

XXXX XXXXXXX XXXXXX XXXXX XXXXXXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Privacy Notice for Muse Podcast, LLC') XXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX gettext(u'Last updated:') XXXXXXXXX XXXXXXXXXXXXXX
        XXX gettext(u'Muse Podcast, LLC is committed to protecting your privacy. This Privacy Notice explains how we collect, use, share, and safeguard your information when you visit our website and register an account.') XXXX
        XXXX gettext(u'Information We Collect') XXXXX
        XXX gettext(u'We collect the following information when you create an account or use our website:') XXXX
        XXXX
          XXXXXXXXXXXX gettext(u'Personal Information:') XXXXXXXXX
            XXXX
              XXXX gettext(u'First Name') XXXXX
              XXXX gettext(u'Last Name') XXXXX
              XXXX gettext(u'Email Address') XXXXX
              XXXX gettext(u'Birthdate') XXXXX
              XXXX gettext(u'Country') XXXXX
              XXXX gettext(u'Phone Number') XXXXX
              XXXX gettext(u'Gender') XXXXX
            XXXXX
          XXXXX
          XXXXXXXXXXXX gettext(u'Technical Information:') XXXXXXXXX
            XXXX
              XXXX gettext(u'Geolocation') XXXXX
              XXXX gettext(u'IP Addresses') XXXXX
            XXXXX
          XXXXX
          XXXXXXXXXXXX gettext(u'Usage Information:') XXXXXXXXX
            XXXX
              XXXX gettext(u'Data on what you search, view, or click within our website.') XXXXX
            XXXXX
          XXXXX
        XXXXX
        XXXX gettext(u'Purpose of Data Collection') XXXXX
        XXX gettext(u'Muse Podcast, LLC collects this data to:') XXXX
        XXXX
          XXXX gettext(u'Provide, maintain, and improve our website services.') XXXXX
          XXXX gettext(u'Protect our website and users against fraudulent activities and scams.') XXXXX
          XXXX gettext(u'Generate analytics to enhance user experience.') XXXXX
        XXXXX
        XXXX gettext(u'Data Sharing and Selling') XXXXX
        XXX gettext(u'To keep our services free and advertisement-free, Muse Podcast, LLC may sell aggregated, anonymized data analytics to podcast creators, business partners, or other third parties. We ensure your privacy by anonymizing data, meaning your personal identifiable information (like your name or exact contact details) will never be sold or shared. Your identity is replaced by a unique, randomized number to maintain your anonymity.') XXXX
        XXXX gettext(u'Data Security') XXXXX
        XXX gettext(u'Muse Podcast, LLC employs industry-standard practices and technologies to safeguard your personal information. However, no method of transmission over the internet or electronic storage is 100%% secure, so while we strive to protect your personal information, we cannot guarantee absolute security.') XXXX
        XXXX gettext(u'Consent') XXXXX
        XXX gettext(u'By clicking the checkbox when creating an account, you consent to the collection, use, and sharing practices described in this Privacy Notice.') XXXX
        XXXX gettext(u'Your Rights and Choices') XXXXX
        XXX gettext(u'You have the right to access, correct, or request deletion of your personal data at any time. To exercise these rights or if you have questions about this Privacy Notice, contact us at:') XXXX
        XXX
          XXXX XXXXXXXX XXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
        XXXX gettext(u'Changes to This Privacy Notice') XXXXX
        XXX gettext(u'Muse Podcast, LLC reserves the right to modify this Privacy Notice at any time. Changes will be posted on our website and are effective immediately upon posting.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXX XXXX XXXXXXXXX XXX XXXXX XXX
XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X

  XXXXXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX X
  XXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX X
 XX XXXX XXX XXXXX XXXX XX XXX XXXXXX XXXXX XX XXX XXXX XXXXX XXXXX XXXX XX
XXXXXXXXXXXX X XXXXXXXXXXXXXX
XXXXXXXXXXXX X XXXXXXXXXXXX X
  XXXXX X X XXXXX
  XXXXXX XXX
  XXXXXXXXXX XX XX XXXXXXXX XXXXXXXX XXXXXXX XXX XXXXXX XXXX XX
  
X
XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
  XXXXXX XX XXXXXXXXXXX   XX XXXX XX XXXXXXXXX XXXX XX XXXXXXX XX
  XXXXX X X XXXXX
  XXXXXXXXXX XX
X
XX XXXXXXXXXXX XXXX XXXXXX XXX XXX XXXXX XXXXXXXXXX XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XX XX XXXXXXX XX

XXXXXXXXXX X 
  XXXXXX XXXXXXXX 
  XXXXXXXXXXXXX X XX 
  XXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXX 
  XXXXXXXXXX XXXXXXX
  X
X
  XX XXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXX XX XXXXX XXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XX XXXXXX XXXXXXXXXXXX XXXXXX XXXXX XX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
  X

  XX XXXXXXXXX XXX XXXXXX XXXXX XXXXX XX XXX XXXXX XX XXXXX XXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX  X XXXXXX XXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX  X XXXXXX XXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXX X

  XX XXXX XXXX XXXX XXXXXX XXXX XXXXXXXX XXXXX XXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX

XXXX XXXXXXXXX XX XXX XXX XXXXXXX XX XXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XX XXXXXX XXXXXXXX XXXXXXXXXX
  XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX XXXXXXX
      XX XXXXXXXXXXX XXX XXXXXXXXXXX X
        XXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X XXXX X
        XXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
    XXX
  XXX

  XX XXXXXXXX XXXXXXXXXXXX XXXXX
  XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
    XXX XXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXX
      X
      XXXXX X XXXXXXXXXXXXX XX X
        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XX XXXXXXXXXXX
          XXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXX XXXXXXXX XX XXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            X XXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXX XXXX XXXXXXXX XX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            X
          XX
          XXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
          XXX
      XX XXXXX
    XXX
  X

  XX XXXXXXXX XXXXX XXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
      XX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Passwords match') XXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Passwords do not match') XXXXXXXXX
      X
    X XXXX X
      XXXXXXXXXXXXXXXXXXX X XXX
    X
  X
  XX XXXXXXXXXX XX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  X
XXX
XXXXXXXXX XX X
  XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX   XX XXXXXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX        XX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXX X XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXX
      XX XXX XX XXXX XXXXX XXXXXXXX XXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
      XX XXXX XXX XXXX XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXX X XXXXXXX
      X
    XXX
  X

  XX XXXXXX XXXXX XX XXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX
  XX XX XXX XXXX XXXXXX XXXXX XXXXXXXX XXXXXX XXXX XXXXX XXX XXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX
XXXXXXXXX
BBBBBBBB
