BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX

  XXXX XXXXXX XXXXXX XXXX XXX
  XXX XXXXXXXXXXXXX gettext(u'Submit a Support Ticket') XXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXX
      
      
      
    XXXXXX
    XXXX XXXXXXXXXXXXX
      
      
      
    XXXXXX
    XXXX XXXXXXXXXXXXX
      
      
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      
    XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
       gettext(u'Submit Ticket') 
    XXXXXXXXX
  XXXXXXX

  XXXX XXXX XXXXXXX XXX
  XXX XXXXXXXXXXXXX gettext(u'Your Tickets') XXXXX

  XXXX XXXXXX XXX XXX XXXX XXXXXXX XXXXX XXX
  XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXX XXXXXX XXXXXXXXXXX
      XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XX
    X
    XXXXXXXXXXXXXXXXXXX XXXXX XX X
      XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXX            XXXX     XXXXXXXXXXX
      XXXXXXXXXXXXXX    XXX XXXXX XXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXX XXXXX XX X
      XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXX             XXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXX XXXXX XX X
      XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
    X
      XX XXXXXX XXXXX X XXXX XX XXXXXXXXXXXXX XXXXX XX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX            XXXX     XXXXXXXXXXX
        XXXXXXXXXXXXXX    XXX XXXXX XXXXXXX XXXXXXXXXXX
    X
    XX XXXX XXXXX X XXXX XX XXXXXXXXXXXXX XXXXX XX XX
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX            XXXXXXX XXXXXXXXXXX
    X
    XX XXXXXX XXXXX X XXXX XX XXXXXXXXXXXXX XXX XXXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
    X
     XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX      XX XXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX  XX XXXX XXXXXX XX
        XXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXX XXXX XXXXXXXXXXX    XX XXXXXXX XXXX XX
        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX X XXXX XXXXXXXXXXX             XX XXXXXXX XX XX
    X
  XXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
        XXXX
          XXXX gettext(u'Ticket #') XXXXX
          XXXX gettext(u'Subject') XXXXX
          XXXX gettext(u'Message') XXXXX
          XXXX gettext(u'Submitted') XXXXX
          XXXX gettext(u'Last Reviewed') XXXXX
          XXXX gettext(u'Status') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBB BB BBBBBBB
          XXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFXX
                
              XXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFXX
                
              XXXXXXX
            XXXXX
            XXXXFFFFFFFFFFF FFFFXXXXX
            XXXXFFFFFFFFFFF FFFFFFFFFFFFFFFXXXXX
            XXXXXXXXX
          XXXXX
        BBBBB
          XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'You haven’t submitted any tickets yet.') 
            XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXX XXXXX XXX XXXXXXX X XXXXXXXXXX XXXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          BB BBBBBBB
             gettext(u'Success') 
          BBBB
             gettext(u'Failure') 
          BBBBB
        XXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
          XXXXXXX
            XXXX
              XXX XXXXXXXXXXX XXXXXX
                BB BBBBBBB
                   gettext(u'Your support ticket has been submitted successfully!') 
                BBBB BBBBBBBBBB BB BBBBBB
                   gettext(u'Your support ticket was unsuccessful, file size is too large, needs to be ≤ 2 MB.') 
                BBBB BBBBBBBBBB BB BBBBBB
                   gettext(u'Your support ticket was unsuccessful, file type incorrect, only (JPG/PNG/GIF) are accepted.') 
                BBBB BBBBBBBBBB BB BBBBBB
                   gettext(u'Your support ticket was unsuccessful, file type incorrect (only JPG/PNG/GIF) and file size is too large (≤ 2 MB).') 
                BBBB BBBBBBBBBB BB BBBBBBB
                XX XXXXXXXXXXXXX
                     gettext(u'You’ve reached your limit of %(limit)s open tickets (%(open_count)s/%(limit)s). Please wait for one to complete or cancel before opening a new one.') SSSSSS SSSSSSS SSSS SSSSS SS SSSSSSSSS SSSS SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS SSSS SSS SSS SS SSSSSSSS SS SSSSSS SSSSSS SSSSSSS S SSS SSSS
                XXXX
                BBBBB
              XXXXX
            XXXXX
          XXXXXXXX
        XXXXXXXX
      XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXXXXX
                XXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXX
                        XXXXXXX XXXXXXXXXXXXX
                                XXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'OK') 
                        XXXXXXXXX
                    XXXXX
                XXXXX
            XXXXXXXX
        XXXXXXXX
    XXXXXX

    XXXXXX
  XXXXXX
XXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXX XXXXX XX X XXXXXXXXXX XXXX XXXXXXXX XX XXXXX XXX XX XXXXXXXXXX XXXXX
    XXXXX XXXXXXXXX X FFFFFFFFFFFFFFFFFF XX FFFFFFFFFFFFFFFFFFX
    XX XXXXXXXXXXX X
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB
