
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
  XXXX gettext(u'Login Cancelled') XXXXX
  XX XXXXXXXXXXXXX
     gettext(u'You decided not to sign in with that external account.') 
  XXXX
  XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXX
     gettext(u'Back to Login') 
  XXXX
XXXXXX
BBBBBBBB
