BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXX X XXXX XXXX gettext(u'Confirm your Muse Podcast account') XXXXX

      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u"You're almost done! Confirm your account by clicking the button below:") 
      XXXX

      XX XXXXXXXXXXXXXXXXXX XXXX
        XX XXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'Confirm my account') 
        XXXX
      XXXX

      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'Or paste this link in your browser:') XXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX

      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'This link expires in 24 hours.') 
      XXXX

      XX XXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Worm regards,') XXXX
        XXXX XXXXXXX XXXX
      XXXX
    XXXXXX
  XXXXXXX
XXXXXXX
