BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXX gettext(u'Confirm Your Email') XXXXX

  BB BBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXX
       gettext(u'\n      Confirm the email address <strong>%(email)s</strong> to activate your account.\n      ') 
      SSSSSSS SSS SSSSS SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSSSSSS SSSS SSSSSSSS
      
    XXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
         gettext(u'Confirm Email') 
      XXXXXXXXX
    XXXXXXX

  BBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
       gettext(u'This confirmation link is invalid or has expired.') 
    XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
       gettext(u'Start over') 
    XXXX
  BBBBB
XXXXXX
BBBBBBBB
