
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX gettext(u'Enter OTP Token') XXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Submit') XXXXXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB
