
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXX gettext(u'Login') XXXXX

  
  XXXX XXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Sign in with Google') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXXXXX XXXX XXXXXXXXXX  gettext(u'Sign in with X') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Sign in with GitHub') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX

  XXXXX
  XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'or sign in with an account manually') XXXX

  
  XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
    BBBBBBBBBB
    

    XXXX XXXXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Email or Username') XXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFF
      
    XXXXXX

    XXXX XXXXXXXXXXXXX
  XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Password') XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Show password') XX
      XX XXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  
XXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Log In') XXXXXXXXX
  XXXXXXX

  XX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Forgot your password?') XXXX
  XXXX
  XX XXXXXXXXXXXXX
     gettext(u"Don't have an account?")  XX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Sign up') XXXX
  XXXX
XXXXXX


XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

XXXXXXX
  XX XXXXXXXXXXXXX XXXXXX XXX XXXX XXXXXX XX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXX X X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XX X
  XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X

  XX XXXXX XXXX XXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXX
  X
  XX XXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXX XX XXXXX XXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XX XXXXXX XXXXXXXXXXXX XXXXXX XXXXX XX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
  X

  XX XXXXXXXXX XXX XXXXXX XXXXX XXXXX XX XXX XXXXX XX XXXXX XXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX  X XXXXXX XXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX  X XXXXXX XXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXX X

  XX XXXX XXXX XXXX XXXXXX XXXX XXXXXXXX XXXXX XXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXX XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX XXX XXXXXXXXXXX X
      XXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXX X
      XXXXXXXXXX X XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XXX
XXX
XXXXXXXXX
BBBBBBBB
