
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX gettext(u'Reset Your Password') XXXXX
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Reset Password') XXXXXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB
