
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX gettext(u'Password Changed') XXXXX
  XXX gettext(u'Your password has been successfully changed.') XXXX
  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Return to Profile') XXXX
XXXXXX
BBBBBBBB
