
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX gettext(u'Change Password') XXXXX
  XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Change Password') XXXXXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB
