
BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB BB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXX
      XXX XXXXXXXXXXXXX gettext(u'Account Locked') XXXXX
      XX XXXXXXXXXXX XXXXXXXXXXXX
         gettext(u'For your security, we’ve temporarily locked your account after multiple failed login attempts.') 
      XXXX

      XXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
          XXXXX
            XXXXXXXX gettext(u'Please wait and try again.') XXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX
               gettext(u'Time until unlock:') 
              XXXXX XXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFXXXXXXXXX
            XXXXXX
          XXXXXX
          BB BBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX
               gettext(u'Unlocks at')  FFFFFFF FF F FFF F FF
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX XXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Reset Password') XXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Back to Login') XXXX
      XXXXXX

      XX XXXXXXXXXXX XXXXX XXXXXXXXXXXX
         gettext(u'If you think this was a mistake, contact support at %(email)s.') SS SSS SSSSS SSSS SSS S SSSSSSSS SSSSSSS SSSSSSS SS SSSSSSSSSS
      XXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX
  XX XXXXX XXXX XXXX XXXX XX XXXX XXXXXX XX
  XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
XXXXXXXX

XXXXXXXX
  XX XXXX XXXXXXXXX
  XXXXXXXXX XX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXX XXXXXXX
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXX

    XXXXXXXX XXXXXX X
      X X XXXXXXXXXXX XXXXX
      XXXXX X X XXXXXXXXXXXX X XXXXXX
      XXXXX X X XXXXXXXXXXXXX X XXXXX X XXXX
      XXXXX X X X X XXX
      XXXXXX X X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXX X
      XXXXXXXXXXXXXX X XXXXXXXXXX
      XX XXXXX X XX X
        XXXX XX XX
        XXXXXXXXXXXXXXXX XXXXXX
      X
    X
    XXXXXXX
  XXXXX
XXXXXXXXX
BBBBBBBB
