BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBB
  XXXX gettext(u'Enter OTP') XXXXX
  XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Submit OTP') XXXXXXXXX
  XXXXXXX
BBBBBBBB
