name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Run Gitleaks
      - name: Run Gitleaks secret scanner
        uses: zricethezav/gitleaks-action@v1
        with:
          args: detect --source . --exit-code 1
